### ISSUE TITLE
[API] Login with certificate(identifier, password)| Google, Facebook.

### ISSUE THREAD

**Issue by tzung243** [tzung243/se2022-8.2#2]
# Task

Description: Login user by multi JWT, Google, Facebook.

- [ ] Login system with certificate(identifier, password). 
- [ ] Login system with Google(Config Google Developer).
- [ ] Login system with Facebook(Config Facebook Developer). 

🙋‍♂️: When config Google, Facebook Auth requirement Hosting deploy production(By return from callback OAuth2).

# Note Config Strapi

![Image](https://user-images.githubusercontent.com/92531750/208164807-b9acdd81-4485-43ec-83e3-22a2d2490e20.png)

- Enable **connect** local & **callback** of plugin `users-permissions`.
- Role of API is Public role.

# Note API

### URL

`{{SERVER_URL}}/api/auth/local`

$SERVER_URL: This is URL of backend server with `Development` environment, it's: http://localhost:1337.

### Header 

```
Content-Type: application/json
```

or

```
Content-Type: application/form-data
```

### Body

```json
{
    "identifier": "xxx@gmail.com",
    "password": "***"
}
```

### Response 

Code 200:

```json
{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjY0MTYyMjIxLCJleHAiOjE2NjY3NTQyMjF9.aSGrRHpZHiKH1c5aDx_EDtvvPKj-HfPSc38MSZ6LNZk",
    "user": {
        "id": 3,
        "username": "***",
        "email": "***@gmail.com",
        "provider": "local",
        "confirmed": true,
        "blocked": false,
        "deletedAt": null,
        "createdAt": "***",
        "updatedAt": "***"
    }
}
```

Code 400: When not confirm email.

```json
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ApplicationError",
        "message": "Your account email is not confirmed",
        "details": {}
    }
}
```
